### ISSUE TITLE
bug hunting

### ISSUE THREAD

**Issue by nathanieltarshish** [nathanieltarshish/CM2p6convert#1]
Replies to @rabernat:
> How exactly did you do this? Can you share the code you are using to read / write the mitgcm .data files?
> 
> There could be an issue with the array shape and orientation.
> 

[Here](https://github.com/nathanieltarshish/CM2p6convert/blob/master/velocity_regrid/nc2data.py) is the code I used to write the mitgcm .data files. To verify, I read in both the netcdf and .data input using

```python
ncpath = 'V0000000000.nc'
ncdata = nc.Dataset(ncpath)
V = ncdata['v'][...]
filename = 'V.0000000000.data'
prec = 32
Vdata = np.fromfile(filename, dtype='>f%g' % (prec/8))
print len(Vdata) == np.shape(V)[0]*np.shape(V)[1]
Vdata_reshape = Vdata.reshape(np.shape(V)[0],np.shape(V)[1])
ncdata.close()
```
I then element-wise compared `Vdata_reshape` and `V`. 

> Is there any way I can log on to the machine where you are running this in order to inspect your setup?

Not that I can think of, however, I could move it the setup to yeti. Want to try that?

> Create a data.diagnostics file 

Sounds good, will work on.

**Comment by rabernat** [comment]
> I then element-wise compared Vdata_reshape and V.

This just verifies that the binary data is the same as the netcdf data. It doesn't verify that MITgcm is seeing the correct fields. There could possibly be some issues with C vs Fortran array order. That's why I think it will be useful to output the velocity field directly from the model. 

Could you post the netcdf file and U / V binary files online somewhere I can download them?

**Comment by nathanieltarshish** [comment]
> Could you post the netcdf file and U / V binary files online somewhere I can download them?

I transfered a set of binary and netcdf files to `/net2126/CM2p6_velocity_files` on yeti. Is that convenient for you to access? If not, I can figure out another way.

**Comment by rabernat** [comment]
perfect, thanks

**Comment by nathanieltarshish** [comment]
Also, I put the input and output of the simulation in `.../net2126/CM2p6_patch`.

**Comment by nathanieltarshish** [comment]
In regards to outputting U/V as diagnostics, I believe that I am already doing this in the `DiagVel_1day.*.data` files (included in the `CM2p6_patch` folder). Will investigate...

**Comment by nathanieltarshish** [comment]
Checked `UVEL`, `VVEL, `Depth` diagnostics, all three look like non-sense. I think your hypothesis about array ordering was correct. 
For instance 
```python
depth = np.array(ds['Depth'][:,:])
plt.matshow(depth)
>>> nonsense
depth_reshape = depth.reshape(3600,2107)
plt.matshow(depth_reshape)
>>> correct bathymetry plot
```
and so forth with UVEL and VVEL. Looks like I should transpose the arrays, recreate the input files, and then rerun the simulation. Thanks for your help and suggestions.

**Comment by rabernat** [comment]
Nice work tracking it down! Hopefully it is simply a question of properly transposing the data.

FYI, for reading MITgcm mds output files in python, I recommend using my [xmitgcm](http://xmitgcm.readthedocs.io/) package.
